### PR TITLE
uids in fetch instead numbers, remove miss_no_uid arg from fetch

### PR DESCRIPTION
**Pull request by ikvk**

### CODE REVIEW

**Comment by dimitrisstr** [comment]
1. You forgot to update the fetch_by_pages.py example.
2. Maybe the numbers methods should be removed. It is only used in the uids method. You could change the self.client.search to self.client.uid as shown here https://stackoverflow.com/questions/63685324/searching-for-utf-8-encoded-subjects-with-imaplib

**Comment by ikvk** [comment]
1. fetch_by_pages is not broken, and numbers method may be useful.
2. I wrote new uids.
3. tests is ok

@dimitrisstr  Can you try it?

**Comment by dimitrisstr** [comment]
There is a case that `self.client.uid('fetch', ...` may try to fetch an email, that no longer exists. In this case it returns `('OK', [None])` or `('NO', [b'Some of the requested messages no longer exist.'])`, and your fetch method returns an empty MailMessage or an exception.  Perhaps, you could check if the list is equal to [None] before creating a MailMessage.

**Comment by ikvk** [comment]
1. Some of the requested messages no longer exist: ​This error is caused by a well-known bug in the IMAP implementation used by your email server. This typically affects IMAP servers known as Scalix email servers. So I will not proc it.
2. I have fixed _fetch_by_one


@dimitrisstr, try it now

**Comment by dimitrisstr** [comment]
I think that now, the pull request is ready to be merged. Thank you for your work and this great library.

**Comment by ikvk** [comment]
Thank you, @dimitrisstr , it is pleasure to work with you.

**Pull request merged**
