### PR TITLE
Add support for size of individual message.

### PR DESCRIPTION
**Pull request by aknrdureegaesr**

### CODE REVIEW

**Comment by ikvk** [comment]
Hi.
RFC822.SIZE Allows the recipient to decide whether to spend resources on reading external data.
If you already received data by BaseMailBox.fetch, this value is not matter.
You can get message size by that: len(bytes(msg.obj))
Actually sizes are different, for one example message:
- len(bytes(msg.obj)) - 10297
- len(str(msg.obj)) - 10295
- RFC822.SIZE - 10442

    
Tell me about your usecase.

**Comment by aknrdureegaesr** [comment]
Sure.

I know that very few big messages consume a lot of space in my space-limited IMAP account. I wrote a jupyter notebook to analyze the situation.

The notebook goes through all 30000-some messages in my IMAP account, sorts them by size, and tells me how many message I have that are smaller than an particular size and how much of the total mailbox space (approximately) those messages consume:

2020-09-29_size2total_all

Here is the same chart, restricted to the interesting part showing the big mails:

2020-09-29_size2total_bigones

This tells me that the 1 % largest messages in my mailbox consume more than 25 % of the mailbox space.

Here is the Python code that does the basic data acquisition. It takes a while to run...

```
from imap_tools import MailBox

from os import environ

if "IMAP_HOST" not in environ or "IMAP_USER" not in environ or "IMAP_PASSWD" not in environ:
    raise RuntimeError("You need to set the environment variables IMAP_HOST IMAP_USER IMAP_PASSWD "
                       "before starting jupyter.")

imap_host = environ["IMAP_HOST"]
imap_port = int(environ.get("IMAP_PORT", "993"))
imap_starttls = "IMAP_STARTTLS" in environ
imap_user = environ["IMAP_USER"]
imap_passwd = environ["IMAP_PASSWD"]

size2count = {}

with MailBox(imap_host, port=imap_port, starttls=imap_starttls).\
   login(imap_user, imap_passwd) as mbox:
    folders = [folder_info["name"] for folder_info in mbox.folder.list()]
    for folder in folders:
        mbox.folder.set(folder)
        for mes in mbox.fetch(headers_only=True, mark_seen=False):
            size = mes.size
            if size in size2count:
                size2count[size] += 1
            else:
                size2count[size] = 1
```

**Comment by ikvk** [comment]
To analyze email size at server side you can use https://github.com/ikvk/imap_tools#search-criteria size_gt, size_lt keys. And to analyze email size at client side you can use len(bytes(msg.obj)), len(str(msg.obj)) and maybe something else. So, there is no unambiguous approach to get message size at client side (or is there?).

**Comment by aknrdureegaesr** [comment]
Several different paths can be taken, leading to different results.

"Search criteria" restricts the number of messages. But my plan was to draw a big picture from _all_ messages in my IMAP account. So I reasoned "search criteria" won't help me here.

I also reason `msg.obj` will not give meaningful results unless I download the full message. Or would it? As you can see, my approach  fetches the headers only. I believe this to be much faster.

Do you find any fault with that reasoning? I.e., any chance for me to learn something here?

It indeed is slow enough to fetch the complete headers for 30,000 some messages. I consider fetching only the sizes, rather than the full headers for each message. But that would require more coding. What I have now works for now.

**Comment by ikvk** [comment]
I see now that size really useful. I missed headers_only in your example. I will check all and will release it soon.

**Comment by ikvk** [comment]
I  have fixed bug and released.I  have fixed bugs and released version. Thanks for participating. Good luck!

**Pull request merged**
