### PR TITLE
Added gmail label support 

### PR DESCRIPTION
**Pull request by Foosec**
Added X-GM-LABELS Query support

### CODE REVIEW

**Comment by ikvk** [comment]
Not a part of imap.

**Comment by Foosec** [comment]
sorry, thought it was a significant enough of a provider to add it.

**Comment by ikvk** [comment]
May you tell me about use case of it?

**Comment by Foosec** [comment]
Ofcourse, i can give you ours.

Google allows automatic filters to be setup based on incoming mail paramaters, what we do is have gmail automatically assign labels based on who sent it, and its contents. This works quite well, allows for in gmail filtering for humans and with this makes it very easy to filter out which mails are of interest to the program. Thats i suppose just 1 usecase. One could also be where humans set labels and thats a "signal" for some automated process to process that email.

**Comment by ikvk** [comment]
mailbox.folder.list():

{'flags': ('\\HasNoChildren',), 'delim': '/', 'name': 'INBOX'}
{'flags': ('\\HasChildren', '\\Noselect'), 'delim': '/', 'name': '[Gmail]'}
{'flags': ('\\HasNoChildren', '\\Important'), 'delim': '/', 'name': '[Gmail]/Важное'}
{'flags': ('\\All', '\\HasNoChildren'), 'delim': '/', 'name': '[Gmail]/Вся почта'}
{'flags': ('\\HasNoChildren', '\\Trash'), 'delim': '/', 'name': '[Gmail]/Корзина'}
{'flags': ('\\HasNoChildren', '\\Sent'), 'delim': '/', 'name': '[Gmail]/Отправленные'}
{'flags': ('\\Flagged', '\\HasNoChildren'), 'delim': '/', 'name': '[Gmail]/Помеченные'}
{'flags': ('\\HasNoChildren', '\\Junk'), 'delim': '/', 'name': '[Gmail]/Спам'}
{'flags': ('\\Drafts', '\\HasNoChildren'), 'delim': '/', 'name': '[Gmail]/Черновики'}
{'flags': ('\\HasChildren',), 'delim': '/', 'name': 'test'}
{'flags': ('\\HasNoChildren',), 'delim': '/', 'name': 'test/base'}
{'flags': ('\\HasNoChildren',), 'delim': '/', 'name': 'test/temp1'}
{'flags': ('\\HasNoChildren',), 'delim': '/', 'name': 'test/temp2'}

Result is empty:
```
for msg in mailbox.fetch(Q(gmail_labels='test/base')):
    print(msg.uid, msg.subject, msg.date_str)
```

Give 6 emails:
```
mailbox.folder.set('test/base')
for msg in mailbox.fetch():
    print(msg.uid, msg.subject, msg.date_str)
```

How do you use it?

**Comment by ikvk** [comment]
May you show me how you will use it with imap_tools?

**Comment by Foosec** [comment]
Sorry for the late reply,

```python
with mail.MailBox("imap.gmail.com").login(imap_user, imap_pass) as mbox:
    label_msgs = mbox.fetch(Q(gmail_labels="Foobar", seen=False), mark_seen=True)
```

Are you sure you are using gmail labels? As in have them on any mail? They work different to folders. https://support.google.com/mail/answer/118708?co=GENIE.Platform%3DDesktop&hl=en

**Comment by ikvk** [comment]
1. fix setup.py 
2. rename gmail_labels -> gmail_label
3. update QueryTest.test_converters

**Comment by ikvk** [comment]
4. update readme

**Comment by ikvk** [comment]
good work

**Comment by MattSidney** [comment]
@Foosec will this allow for applying labels via imap_tools or is this for just retrieving them?

**Comment by ikvk** [comment]
@MattSidney 
This is for search by them

**Comment by MattSidney** [comment]
thanks @ikvk, is there also functionality to add labels?

**Comment by ikvk** [comment]
@MattSidney I have no info

**Pull request merged**
